### ISSUE TITLE
demo breaks after running a few commands

### ISSUE THREAD

**Issue by japhir** [simonmichael/hledger#2094]
I just tried running the new demos but run into an issue at some point halfway through the demo.

Same happens at other points in the other demos.
```
$ hledger demo 1
playing: 1) The easiest way to start a journal (add)
space to pause, . to step, ctrl-c to quit
................................................................................................................................................................................................

~$ hledger files
The hledger journal file "/Users/simon/.hledger.journal" was not found.
Please create it first, eg with "hledger add" or a text editor.
Or, specify an existing journal file with -f or LEDGER_FILE.
~$ # No hledger data. Goal: use the add command to start a journal file
~$ # and tell hledger about my first account: my wallet.
~$ hledger add
Creating hledger journal file "/Users/simon/.hledger.journal".
Adding transactions to journal file /Users/simon/.hledger.journal
Any command line arguments will be used as defaults.
Use tab key to complete, readline keys to edit, enter to accept defaults.
An optional (CODE) may follow transaction dates.
An optional ; COMMENT may follow descriptions or amounts.
If you make a mistake, enter < at any prompt to go one step backward.
To end a transaction, enter . when prompted.
To quit, enter . at a date prompt or press control-d or control-c.
Date [2023-03-15]: 
Description: opening balances
Account 1: cash
Amount  1: equity
Amount  2 [$-50.25]: 
Account 3 (or . or enter to finish this transaction): 
2023-03-15 opening balances
    cash            $50.25
    equity         $-50.25

Save this transaction to the journal ? [y]: 
Saved.
Starting the next transaction (. or ctrl-D/ctrl-C to quit)
Date [2023-03-15]: .
~$ hledger files
/Users/simon/.hledger.journal
~$ cat .hledger.journal
; journal created 2023-03-15 by hledger

2023-03-15 opening balances
    cash            $50.25
    equity         $-50.25
~$ 
Traceback (most recent call last):
  File "/usr/bin/asciinema", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/asciinema/__main__.py", line 254, in main
    code = command.execute()
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/asciinema/commands/play.py", line 33, in execute
    code = self.play()
           ^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/asciinema/commands/play.py", line 44, in play
    self.player.play(
  File "/usr/lib/python3.11/site-packages/asciinema/player.py", line 71, in play
    self._play(
  File "/usr/lib/python3.11/site-packages/asciinema/player.py", line 187, in _play
    time_, event_type, text = next_event()
                              ^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/asciinema/player.py", line 127, in next_event
    return events_iter.__next__()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/asciinema/asciicast/events.py", line 41, in <genexpr>
    return ([delay / speed, type_, data] for delay, type_, data in events)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/asciinema/asciicast/events.py", line 21, in to_absolute_time
    for frame in events:
  File "/usr/lib/python3.11/site-packages/asciinema/asciicast/events.py", line 31, in <genexpr>
    return (
           ^
  File "/usr/lib/python3.11/site-packages/asciinema/asciicast/events.py", line 9, in to_relative_time
    for frame in events:
  File "/usr/lib/python3.11/site-packages/asciinema/asciicast/v2.py", line 39, in events
    yield json.loads(line)
          ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)
There was a problem. Is asciinema installed ?
callProcess: asciinema "play" "-s2" "-i10" "/tmp/hledger-cast1551302-0" (exit 1): failed
```

hledger --version
hledger 1.31, linux-x86_64
I'm on Arch Linux
using asciinema version 2.3.0

**Comment by japhir** [comment]
Here's the output for demo 3

<details> <summary> demo 3 </summary>

```
hledger demo 3
playing: 3) Show account balances and changes (balance)
space to pause, . to step, ctrl-c to quit
................................................................................................................................................................................................

~$ hledger balance   # show account balances
              $50.25  cash
             $-50.25  equity
--------------------
                   0  
~$ hledger balance cash   # show just cash account
              $50.25  cash
--------------------
              $50.25  
~$ 
Traceback (most recent call last):
  File "/usr/bin/asciinema", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/asciinema/__main__.py", line 254, in main
    code = command.execute()
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/asciinema/commands/play.py", line 33, in execute
    code = self.play()
           ^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/asciinema/commands/play.py", line 44, in play
    self.player.play(
  File "/usr/lib/python3.11/site-packages/asciinema/player.py", line 71, in play
    self._play(
  File "/usr/lib/python3.11/site-packages/asciinema/player.py", line 187, in _play
    time_, event_type, text = next_event()
                              ^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/asciinema/player.py", line 127, in next_event
    return events_iter.__next__()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/asciinema/asciicast/events.py", line 41, in <genexpr>
    return ([delay / speed, type_, data] for delay, type_, data in events)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/asciinema/asciicast/events.py", line 21, in to_absolute_time
    for frame in events:
  File "/usr/lib/python3.11/site-packages/asciinema/asciicast/events.py", line 31, in <genexpr>
    return (
           ^
  File "/usr/lib/python3.11/site-packages/asciinema/asciicast/events.py", line 9, in to_relative_time
    for frame in events:
  File "/usr/lib/python3.11/site-packages/asciinema/asciicast/v2.py", line 39, in events
    yield json.loads(line)
          ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)
There was a problem. Is asciinema installed ?
callProcess: asciinema "play" "-s2" "-i10" "/tmp/hledger-cast1564254-0" (exit 1): failed
```

</details>

**Comment by simonmichael** [comment]
I see the same on mac with asciinema 2.3.0. Possibly its CLI changed recently ? Needs investigation, a fix in hledger, and some thought about how to minimise this in future.

**Comment by simonmichael** [comment]
This is under investigation at https://github.com/asciinema/asciinema/issues/577 . For now, the workaround for hledger users is to downgrade your asciinema from 2.3 to 2.2. (Or install asciinema 2.2 first in PATH, eg with a script similar to the below.)

```shell
#!/usr/bin/env bash
PYTHONPATH=~/src/asciinema2.2 python3 -m asciinema "$@"
```

**Comment by simonmichael** [comment]
Fixed in hledger master, or by upgrading asciinema 2.3.0 to 2.4.0.
